networks:
  sol-solution_net:
    driver: bridge

services:
  dev-db:
    image: postgres:17
    container_name: res-sol_solution_dev
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev-root
      POSTGRES_DB: dev_sol_solution_db
    ports:
      - "5434:5432"
    networks:
      - sol-solution_net

  prod-db:
    image: postgres:17
    container_name: res-sol_solution_prod
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: prod_sol_solution_db
    ports:
      - "5435:5432"
    networks:
      - sol-solution_net

  adminer:
    image: adminer
    container_name: adminer_sol-solution
    restart: always
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: dev-db
    networks:
      - sol-solution_net
